When typo correction for an id-expression finds a type (or Objective-C class), provide a suggestion for the type or class found. However, since we can't recover properly in this case, don't provide a fix-it hint. Example:
test/FixIt/typo.m:8:3: error: use of undeclared identifier 'NSstring';
did you
      mean 'NSString'?
  NSstring *str = @"A string";
  ...
  ^
1 diagnostic generated.

llvm-svn=92379