Add a missing enumerator to this switch. Currently its in the assert-path code, as previously we would have fallen off the end of the function, but please review and let me know if this should go somewhere else.
This fixes a Clang warning:
lib/MC/MCMachOStreamer.cpp:201:11: error: enumeration value 'MCSA_IndirectSymbol' not handled in switch [-Werror,-Wswitch-enum]
  switch (Attribute) {
          ^
1 error generated.

llvm-svn=135976