Change GotoStmt's to have a pointer to the LabelStmt instead of a pointer to the label identifier.  Handle fwd references etc.  This allows us to detect uses of undefined labels and label redefinitions, such as:
t.c:2:12: error: redefinition of label 'abc'
  abc: ;   abc:
           ^
t.c:2:3: error: previous definition is here
  abc: ;   abc:
  ^
t.c:12:12: error: use of undeclared label 'hijl'
      goto hijl;
           ^

llvm-svn=39509